# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Please follow the issue template to help us help you ğŸ‘ğŸ‰ğŸ˜„

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! `Dangerbot` will test out your code and reply in a bit with some pointers and requests. There may be some errors, but don't worry! We're here to help! ğŸ‘ğŸ‰ğŸ˜„

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸

# It is recommend to include as many gifs and emojis as possible
