# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue! This space is [protected by our Code of Conduct](https://publiclab.org/conduct) - and we're here to help.
  Please follow the issue template to help us help you ğŸ‘ğŸ‰ğŸ˜„
  If you have screenshots [or a gif](https://publiclab.org/gifs/) to share demonstrating the issue, that's really helpful! ğŸ“¸
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request!  This space is [protected by our Code of Conduct](https://publiclab.org/conduct) - and we're here to help.
 `Dangerbot` will test out your code and reply in a bit with some pointers and requests.
 There may be some errors, **but don't worry!** We'll work through them with you! ğŸ‘ğŸ‰ğŸ˜„
 
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸ 
 Your code will likely be published to PublicLab.org in the next few days. 
 In the meantime, can you tell us your Twitter handle so we can thank you properly?
 Now that you've completed this, you can help someone else take their first step!
 See: [Public Lab's coding community!](https://code.publiclab.org)

# It is recommend to include as many gifs and emojis as possible
  
