# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thanks for opening your first issue here! Please follow the issue template to help us help you ğŸ‘ğŸ‰ğŸ˜„
  If you have screenshots to share demonstrating the issue, that's really helpful! ğŸ“¸ You can [make a gif](https://www.cockos.com/licecap/) too!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request! `Dangerbot` will test out your code and reply in a bit with some pointers and requests.
 There may be some errors, **but don't worry!** We're here to help! ğŸ‘ğŸ‰ğŸ˜„

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸ 
 Your code will likely be published to PublicLab.org in the next few days. 
 In the meantime, can you tell us your Twitter handle so we can thank you properly?
 Now that you've completed this, you can help someone else take their first step!
 See: [Public Lab's coding community!](https://code.publiclab.org)

# It is recommend to include as many gifs and emojis as possible
  
