sudo: required

services:
  - docker

install:
  - cp config/database.yml.example config/database.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose build
  - docker-compose run web sleep 5
  - docker-compose run web bash -c "rake db:setup"
  - docker-compose run web bash -c "rake db:migrate"
  - docker-compose run web bower install --allow-root

script:
  - docker-compose run web bash -c "rake test:all"

language: ruby
cache: bundler
