sudo: required

services:
  - docker

git:
    depth: false
  
env:
  - COMPOSE_FILE=./containers/docker-compose-testing.yml

before_install:
  - echo -e "repo_token:\n  $COVERALLS_REPO_TOKEN" >> ./.coveralls.yml
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - cp config/database.yml.example config/database.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec web sleep 5
  - docker-compose logs db
  - netstat -ltpn
  - docker-compose exec web bash -c "rake db:setup"
  - docker-compose exec web bash -c "rake db:migrate"
  - docker-compose exec web yarn --ignore-engines --ignore-scripts --modules-folder ./public/lib
  - docker-compose exec web bash -c "rake assets:precompile"
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then gem install danger danger-junit; fi'

script:
  - docker-compose exec web bash -c "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  - docker-compose exec web bash -c "dpkg -i google-chrome-stable_current_amd64.deb --fix-missing; apt-get -fy install"
#  - docker-compose exec web bash -c "apt-get install google-chrome-stable chromium-chromedriver"
  - docker-compose exec web bash -c "whereis google-chrome-stable"
  - docker-compose exec web bash -c "curl https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip"
  - docker-compose exec web bash -c "unzip chromedriver_linux64.zip"
  - docker-compose exec web bash -c "mv chromedriver /usr/local/bin/chromedriver"
  - docker-compose exec web bash -c "chmod +x /usr/local/bin/chromedriver"
  - docker-compose exec web bash -c "whereis chromedriver"
  - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rake test:all"
  - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rails test -d"
  # Capybara can't work with Passenger on Travis, hence disabling system test on
  # production until we change over to a Rack server. (jywarren undoing to further test)
  - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rails test:system"
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>' > output.xml
  - tail -n +2 -q ./test/reports/TEST*.xml >> output.xml
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi'
  
#before_script:
#  - docker-compose exec web bash -c "ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver"
#   - export DISPLAY=:99.0

# addons:
#   apt:
#     packages:
#       - chromium-chromedriver
#   chrome: stable
