sudo: required

services:
  - docker

before_install:
  - echo -e "repo_token:\n  $COVERALLS_REPO_TOKEN" >> ./.coveralls.yml

install:
  - cp config/database.yml.example config/database.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose build
  - docker-compose run web sleep 5
  - docker-compose run web bash -c "rake db:setup"
  - docker-compose run web bash -c "rake db:migrate"
  - docker-compose run web bower install --allow-root
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then gem install danger danger-junit; fi'

script:
  - docker-compose run -e CI=TRUE web bash -c "GENERATE_REPORT=true rake test:all"
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>' > output.xml
  - tail -n +2 -q ./test/reports/TEST*.xml >> output.xml
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi'
