sudo: required

language: generic

services:
  - docker

git:
    depth: false
  
env:
  global:
    - COMPOSE_FILE=./containers/docker-compose-testing.yml
  matrix:
    - TASK="TEST_TYPE=mocha rake test:all"
    - TASK="TEST_TYPE=unit rails test test/unit"
    - TASK="TEST_TYPE=functional rails test test/functional"
    - TASK="TEST_TYPE=integration rails test test/integration"
    - TASK="TEST_TYPE=system rails test:system"

before_install:
  - echo -e "repo_token:\n  $COVERALLS_REPO_TOKEN" >> ./.coveralls.yml
  
branches:
  only:
    - master
    - unstable

install:
  - cp config/database.yml.example config/database.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec web sleep 5
  - netstat -ltpn
  - docker-compose exec web bash -c "rake db:setup"
  - docker-compose exec web bash -c "rake db:migrate"
  - docker-compose exec web bash -c "rake assets:precompile"
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash -c "docker-compose exec web gem install danger danger-junit google-cloud-storage"; fi'

script:
  - docker-compose exec web bash -c 'echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > /tmp/credentials.json' # needs to be a path to a json file, so we shuffle...
  - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true $TASK"
  - if [ $TASK != "rake test:all" ]; then
      echo -e '<?xml version="1.0" encoding="UTF-8"?>' > output.xml;
      tail -n +2 -q ./test/reports/TEST*.xml >> output.xml;
    fi
  - if [ $TRAVIS_PULL_REQUEST != "false" ]; then
      docker-compose exec web danger --verbose;
    fi
