sudo: required

services:
  - docker

before_install:
  - echo -e "repo_token:\n  $COVERALLS_REPO_TOKEN" >> ./.coveralls.yml

install:
  - cp config/database.yml.example config/database.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec web sleep 5
  - docker cp config/solr/* "$(docker-compose ps -q solr)":/opt/solr/server/solr/mycores/default/conf/
  - docker-compose logs
  - docker-compose exec web bash -c "rake db:setup"
  - docker-compose exec web bash -c "rake db:migrate"
  - docker-compose exec web bower install --allow-root
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then gem install danger; fi'

script:
  - docker-compose run -e CI=TRUE web bash -c "rake test:all"
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi'
