sudo: required

services:
  - docker

git:
    depth: false
  
env:
  - COMPOSE_FILE=./containers/docker-compose-testing.yml

before_install:
  - echo -e "repo_token:\n  $COVERALLS_REPO_TOKEN" >> ./.coveralls.yml
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - cp config/database.yml.example config/database.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose build
  - docker-compose up -d
  - docker-compose exec web sleep 5
  - docker-compose logs db
  - netstat -ltpn
  - docker-compose exec web bash -c "rake db:setup"
  - docker-compose exec web bash -c "rake db:migrate"
  - docker-compose exec web yarn --ignore-engines --ignore-scripts --modules-folder ./public/lib
  - docker-compose exec web bash -c "rake assets:precompile"
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then gem install danger danger-junit; fi'

script:
  - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rake test:all"
  - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rails test -d"
  - docker-compose exec web bash -c "CI=TRUE GENERATE_REPORT=true rails test:system"
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>' > output.xml
  - tail -n +2 -q ./test/reports/TEST*.xml >> output.xml
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then danger --verbose; fi'
  
before_script:
  - export DISPLAY=:99.0
#  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
