version: "2"
services:
  db:
    image: mariadb:10.2
    network_mode: "service:web"
    environment:
      - MYSQL_DATABASE=plots
      - MYSQL_USER=plots
      - MYSQL_PASSWORD=plots
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ../config/my.cnf:/etc/mysql/my.cnf
      # for configuration 
      - ../../mysql:/var/lib/mysql
      # for persistence
      - ../../dump:/docker-entrypoint-initdb.d
      # for importing a dump
      # if you want to re-import simply put away ../../mysql/*
  redis:
    image: redis:latest
    command: redis-server
  web:
    build: ..
    cap_add:
      - SYS_PTRACE
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - REDIS_URL=redis://redis:6379/0
      - DANGER_GITHUB_API_TOKEN=${DANGER_GITHUB_API_TOKEN}
      - TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
      - TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
      - CI=${CI}
      - TRAVIS=${TRAVIS}
      - CONTINUOUS_INTEGRATION=${CONTINUOUS_INTEGRATION}
      # used to tell if we are in a Travis environment:
      - HAS_JOSH_K_SEAL_OF_APPROVAL=${HAS_JOSH_K_SEAL_OF_APPROVAL}
      - GITHUB_ACTION=${GITHUB_ACTION}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}
      - GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}
      - QT_QPA_PLATFORM=${QT_QPA_PLATFORM}
      - TEST_TYPE=${TEST_TYPE}
    links:
      - redis
    volumes:
      - ..:/app
    restart: unless-stopped
  sidekiq:
    build: ..
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0

