version: "2"
services:
  db:
    image: mariadb:10.2
    environment:
      - MYSQL_DATABASE=plots_$RAILS_ENV
      - MYSQL_USER=plots
      - MYSQL_PASSWORD=plots
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ../config/my.cnf:/etc/mysql/my.cnf
      # for configuration
      - ../../mysql:/var/lib/mysql
      # for persistence
      - ../../dump:/docker-entrypoint-initdb.d
      # for importing a dump
      # if you want to re-import simply put away ../../mysql/*
  web:
    ports:
      - "127.0.0.1:4001:4001"
    build: ..
    command: /bin/bash -c "sleep 5 && /usr/local/bundle/bin/passenger start --max-request-queue-size 200 --max-pool-size 7 --min-instances 7 -p 4001"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - USERNAME=${USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - OAUTH_GOOGLE_APP_KEY=${OAUTH_GOOGLE_APP_KEY}
      - OAUTH_GOOGLE_APP_SECRET=${OAUTH_GOOGLE_APP_SECRET}
      - OAUTH_GITHUB_APP_KEY=${OAUTH_GITHUB_APP_KEY}
      - OAUTH_GITHUB_APP_SECRET=${OAUTH_GITHUB_APP_SECRET}
      - OAUTH_TWITTER_APP_KEY=${OAUTH_TWITTER_APP_KEY}
      - OAUTH_TWITTER_APP_SECRET=${OAUTH_TWITTER_APP_SECRET}
      - OAUTH_FACEBOOK_APP_KEY=${OAUTH_FACEBOOK_APP_KEY}
      - OAUTH_FACEBOOK_APP_SECRET=${OAUTH_FACEBOOK_APP_SECRET}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ..:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    links:
      - redis
      - db
    restart: on-failure:5
  redis:
    image: redis:latest
    command: redis-server
  sidekiq:
    build: ..
    command: bundle exec sidekiq -L log/sidekiq.log
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
      - ..:/app
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
  mailman:
    build: ..
    command: script/mailman_server
    network_mode: "service:web"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - USERNAME=${USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ..:/app
    restart: always
