version: "2"
services:
  db:
    image: mariadb:10.2
    environment:
      - MYSQL_DATABASE=plots
      - MYSQL_USER=plots
      - MYSQL_PASSWORD=plots
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ../config/my.cnf:/etc/mysql/my.cnf
      # for configuration
      - ../../mysql:/var/lib/mysql
      # for persistence
      - ../../dump:/docker-entrypoint-initdb.d
      # mporting a dump
      # if you want to re-import simply put away ../../mysql/*
  web:
    build: ..
    command: /bin/bash -c "sleep 5 && /usr/local/bundle/bin/passenger start -p 4000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - USERNAME=${USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - OAUTH_GOOGLE_APP_KEY=${OAUTH_GOOGLE_APP_KEY}
      - OAUTH_GOOGLE_APP_SECRET=${OAUTH_GOOGLE_APP_SECRET}
      - OAUTH_GITHUB_APP_KEY=${OAUTH_GITHUB_APP_KEY}
      - OAUTH_GITHUB_APP_SECRET=${OAUTH_GITHUB_APP_SECRET}
      - OAUTH_TWITTER_APP_KEY=${OAUTH_TWITTER_APP_KEY}
      - OAUTH_TWITTER_APP_SECRET=${OAUTH_TWITTER_APP_SECRET}
      - OAUTH_FACEBOOK_APP_KEY=${OAUTH_FACEBOOK_APP_KEY}
      - OAUTH_FACEBOOK_APP_SECRET=${OAUTH_FACEBOOK_APP_SECRET}
    volumes:
      - ..:/app
    ports:
      - "127.0.0.1:4000:4000"
    links:
      - db
    restart: unless-stopped
  mailman:
    build: ..
    command: script/mailman_server
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - USERNAME=${USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ..:/app
