version: "2"
services:
  web:
    build: ..
    network_mode: "host"
    command: /bin/bash -c "sleep 5 && passenger start --max-pool-size 9 --min-instances 9 -p 4001 -a 127.0.0.1"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - USERNAME=${USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - OAUTH_GOOGLE_APP_KEY=${OAUTH_GOOGLE_APP_KEY}
      - OAUTH_GOOGLE_APP_SECRET=${OAUTH_GOOGLE_APP_SECRET}
      - OAUTH_GITHUB_APP_KEY=${OAUTH_GITHUB_APP_KEY}
      - OAUTH_GITHUB_APP_SECRET=${OAUTH_GITHUB_APP_SECRET}
      - OAUTH_TWITTER_APP_KEY=${OAUTH_TWITTER_APP_KEY}
      - OAUTH_TWITTER_APP_SECRET=${OAUTH_TWITTER_APP_SECRET}
      - OAUTH_FACEBOOK_APP_KEY=${OAUTH_FACEBOOK_APP_KEY}
      - OAUTH_FACEBOOK_APP_SECRET=${OAUTH_FACEBOOK_APP_SECRET}
    volumes:
      - ..:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    restart: unless-stopped
  mailman:
    build: ..
    network_mode: "host"
    command: script/mailman_server
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - USERNAME=${USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ..:/app
