---
production:
  solr:
    hostname: solr
    port: 8983
    read_timeout: 120
    log_level: WARNING
    path: "/solr/default"
development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: "/solr/development"
  disabled: true
test:
  solr:
    hostname: localhost
    port: 8981
    read_timeout: 120
    log_level: WARNING
    path: "/solr/test"
  disabled: true
